//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int id_Log { get; set; }
        public string LogT { get; set; }
        public string PasT { get; set; }
        public Nullable<int> id_Profal { get; set; }
    
        public virtual Profal Profal { get; set; }
    }
}
